---
- hosts: nodes
  tasks:  
  - name: Remove httpd
    yum: pkg=httpd state=absent
  - name: Remove index.html
    ansible.builtin.file: path=/var/www/html/index.html state=absent
  - name: Close port 80 for httpd
    firewalld: port=80/tcp immediate=yes state=disabled
...
