---
- hosts: nodes
  tasks:  
  - name: Check net.ifnames=0 and write to grub if not exist
    lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames)\"[^\"]+)(\".*)'
      line: '\1 net.ifnames=0\2'
    register: ifnames 
  
  - name: Check biosdevname=0 and write to grub if not exist
    lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* biosdevname)\"[^\"]+)(\".*)'
      line: '\1 biosdevname=0\2'
    register: biosdevname
    
  - name: Write changes to system if ifnames or biosdevname change
    shell: grub2-mkconfig -o /boot/grub2/grub.cfg
    when: ifnames.changed or biosdevname.changed
...
